import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.scss";
import "./css/layout.scss";

// Component CSS
import "./css/componentcss/breadcrumbs.scss"
import "./css/componentcss/flightHeader.scss"
import "./css/componentcss/flightDeparture.scss"
import "./css/componentcss/flightInfo.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="topBar"></div>
        <div className="container">
          <div className="sideBar"></div>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
